### ISSUE TITLE
cowfc server lan error 23904 on dolphin

### ISSUE THREAD

**Issue by sennar83** [EnergyCube/cowfc_installer#2]
I have configured it on a virtual machine of my debian 10 computer and have installed cowfc. I reach the web page correctly but I can't connect to the server using a clean Mario Kart iso. The error it gives me is 23904. I also tried to patch it with wiimmfi v3 using wiimmfi.bat but the result is the same. The server seems to work because if I type on the browser sennarwifi.net or 192.168.1.3 it reaches the web page. What can it be?

**Comment by EnergyCube** [comment]
First, remember that the Debian script has been recently reported EnergyCube@55aa551f383a008430a6b9909cd4d702f097df1e not working on LAN.
I only tested it on a VPS with a domain name.

Your error is very strange and shouldn't happen on CoWFC, [according to Wiimmfi](https://wiimmfi.de/error?e=23904), I think you patched the game incorrectly. Or that you patched it to work with Wiimmfi.

~[Wiimmfi v3 Patch](https://download.wiimm.de/wiimmfi/patcher/) should do the job for us because it offers a patch for Wiimmfi **and for CoWFC (dwc)**. (Old tools has been removed for some reason by Wiimm)~

[WIT](https://wit.wiimm.de/download.html) should do the job.

## To patch the game and connect it to a local VM

You need to use the **Ubuntu script on Ubuntu 16.04** (Since Debian as been reported not working on LAN) and **Virtual Box with a bridge network** adapter.
During the installation when it ask your the server ip or domain put the **Local VM IP**.
This **method requires small changes to Windows network settings** : In the **DNS** settings of your **Windows Network Adapter** add the **VM IP**. (Don't forget to remove it when you don't play)

Patch the game with [WIT](https://wit.wiimm.de/download.html), extract the bin folder (don't use the installer it's completely useless).
Just execute this :

```batch
wit cp . --DEST ../dwc-images/ --update --psel=data --http -vv
```
Or you could technically just use the HTTP cheat code.

## To patch the game and connect it to a VPS with a domain name

You should be able to use Debian 10, but Ubuntu 16.04 has been much more tested.
During the installation when it ask your the server ip put the **External VM IP**.

You can use the [WIT](https://wit.wiimm.de/download.html).
Patch the game with [WIT](https://wit.wiimm.de/download.html), extract the bin folder (don't use the installer it's completely useless).
Simply execute that command be very careful to edit with your domain as the [wit documentation](https://wit.wiimm.de/wit/) says.

Your command should look like this :
```batch
wit cp . --DEST ../dwc-images/ --update --psel=data --http --domain yourdomain.org -vv
```
## Final
I hope it will work, I don't have time to take care of the project because of my studies, but if people want to help to move the project forward, they are more than welcome.
If you have **any questions don't hesitate to ask me**.
**Please let me know here** if any of the solutions work, and which one.

**Comment by EnergyCube** [comment]
No news since two months.
Closing issue, if there is any news don't hesitate to open this issue again.
